### ISSUE TITLE
Add support for AuraComponentBundle

### ISSUE THREAD

**Issue by mshanemc** [afawcett/githubsfdeploy#12]
example repo: https://github.com/mshanemc/getPopular

stuff pulled into the /aura folder under src.  This is how forceCLI does lightning; not implemented in SublimeMavens yet.

Support SVG component, styles, controller, assets, design, rendered, helper, and whatever else the dev console lets you build.  

In the metadata it has its own manifest file for each bundle.

**Comment by afawcett** [comment]
Thanks for this! Will take a look.

**Comment by afawcett** [comment]
Fix deployed.

**Comment by mshanemc** [comment]
@afawcett  you are a shining example of community awesomeness.  Thank you!

**Comment by afawcett** [comment]
@mshanemc Thank you kind sir, means a lot! :+1:

**Comment by up2go-rsoesemann** [comment]
@afawcett I still can't get this working in repos with an aura folder. I made a fork of the Strike components here https://github.com/Up2Go/Strike-Components and modified the README accordingly. But it seems not to recognize the Aura sub folders:

<img width="913" alt="bildschirmfoto 2017-05-19 um 17 30 11" src="https://cloud.githubusercontent.com/assets/8180281/26255082/d9411ba0-3cb8-11e7-8dda-dcae2e76d1b9.png">

The tool also doesn't work if there is no extra `src` folder or any other folders on the same level as `src`.

**Comment by afawcett** [comment]
I'll take a look.

**Comment by up2go-rsoesemann** [comment]
I forgot to add a package.xml. After I added one everything worked perfectly. You can safely close this. Thanks for this great tool.

**Comment by afawcett** [comment]
Ah ha, ok, thanks.
